# Generated by Django 5.2.5 on 2025-09-16 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0003_delete_visit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_time', '-created_at'],
                'indexes': [models.Index(fields=['property', 'date_time'], name='visits_visi_propert_79c8ae_idx'), models.Index(fields=['user', 'date_time'], name='visits_visi_user_id_0f47a6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'property', 'date_time'), name='uniq_visit_user_prop_datetime')],
            },
        ),
    ]
