# Generated by Django 5.1.5 on 2025-09-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('property', '0004_property_agent_alter_property_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='property.property'),
        ),
    ]
