# Generated by Django 5.2.4 on 2025-09-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Propiedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("habitaciones", models.IntegerField()),
                ("banos", models.IntegerField()),
                ("metros_cuadrados", models.IntegerField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=12)),
                ("imagen", models.URLField(blank=True)),
            ],
        ),
    ]
