# Generated by Django 5.2.5 on 2025-09-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_address_alter_propertyimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
